site: Prateek's Blog
title: Prateek's Blog
description: >-
  My Blog
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-IN
repo: https://github.com/NeoDrags/NeoDrags.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Prateek Kesavarapu
  bio: He/Him. I am a 14 year old boy who loves coding and is the owner and creator of the Neosh Shell https://git.io/JceN7. I also love playing Minecraft and am very curious for discovering new things.
  username: NeoDrags # general username
  github: NeoDrags # github username
  twitter:  # twitter username
  email: kesavarapu.prateek@email.com # email adress

# URL settings
url: "https://neodrags.github.io/" #
baseurl:  "" #leave blank if not wishd
permalink: "https://neodrags.github.io/"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: true


